name: Verkon tulevaisuus
favicon: null
layout_spectrum: 0.33703
typography_spectrum: 0.16075
title: 'Mihin menn채채n, mist채 tullaan, mit채 kuuluu, kukkuluuruu'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebf8ff'
    - '#111b24'
    - '#7d7171'
    - '#a19595'
    - '#3c3d42'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
