name: Verkon tulevaisuus
favicon: null
layout_spectrum: 0.73644
typography_spectrum: 0.16075
title: 'Mihin menn채채n, mist채 tullaan, mit채 kuuluu, kukkuluuruu'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3e3a2f'
    - '#605343'
    - '#9b8f7f'
    - '#101010'
    - '#beb7a5'
  brandStrength: 0.717192760668695
  lightness: 0.10284827160649002
  saturation: 0.4727397901006043
  rhythmicContrast: 0.27044886676594615
purpose: []
