name: Verkon tulevaisuus
favicon: null
layout_spectrum: 0.46656
typography_spectrum: 1
title: Ajatuksia verkon ja kaupan tulevaisuudesta
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72972618-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#30716d'
    - '#3c3c3c'
    - '#da6900'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
