name: Verkon tulevaisuus
favicon: null
layout_spectrum: 1
typography_spectrum: 0.90651
title: 'Ajatuksia verkosta, kaupasta, tulevaisuudesta ja asiakaskokemuksesta'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72972618-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2a1f19'
    - '#587267'
    - '#a4947b'
    - '#c2bb9e'
    - '#e1dac6'
  brandStrength: 0
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
