typography_spectrum: 0.90651
color:
  brandColors:
    - '#2a1f19'
    - '#587267'
    - '#a4947b'
    - '#c2bb9e'
    - '#e1dac6'
  brandStrength: 0
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: UA-72972618-1
  facebook: null
  twitter: null
name: Verkon tulevaisuus
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Kirjoittajasta
    id: 1613f99a-a785-45e8-b38e-a9b193f5e599
    type: content
  - name: Totuus Verkkokaupan Tulevaisuudesta.
    id: c7145435-bb14-4ac1-b57b-bda97a1e4924
    type: content
favicon: null
title: 'Ajatuksia verkosta, kaupasta, tulevaisuudesta ja asiakaskokemuksesta'
purpose: []
