name: Verkon tulevaisuus
favicon: null
layout_spectrum: 0
typography_spectrum: 0.16075
title: Ajatuksia verkon ja kaupan tulevaisuudesta
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebf8ff'
    - '#111b24'
    - '#7d7171'
    - '#a19595'
    - '#3c3d42'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
