name: Verkon tulevaisuus
favicon: null
layout_spectrum: 0.49646
typography_spectrum: 0.20476
title: 'Ajatuksia verkosta, kaupasta, tulevaisuudesta ja asiakaskokemuksesta'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72972618-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#30716d'
    - '#3c3c3c'
    - '#da6900'
    - '#000000'
  brandStrength: 0.1875
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
